language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
  - '14'
addons:
  chrome: stable //设置插件，谷歌浏览器最稳定的版本
install:
  - npm install --registry=https://registry.npm.taobao.org
  - echo "install successed"
script:
  - npm run test:prod && npm run build
before_script:
 - "sudo chown root /opt/google/chrome/chrome-sandbox"
 - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
